### ISSUE TITLE
trying to access smb share failed with 'STATUS_SERVER_UNAVAILABLE'

### ISSUE THREAD

**Issue by natke889** [jborean93/smbprotocol#61]
When I am trying to connect to NetApp share I get this message.
After doing more troubleshooting I succeed to access if join the linux machine to domain and using kerberos.
if using ntlm it seem like domain is always NULL

![image](https://user-images.githubusercontent.com/61178350/100546807-f3511980-326b-11eb-995c-ba12d0a0a1fc.png)

Traceback (most recent call last):
  File "smb_test.py", line 3, in <module>
    smbclient.register_session('192.168.35.101', username='KOKO', password='Netapp1!')
  File "/usr/local/lib/python3.6/site-packages/smbclient/_pool.py", line 348, in register_session
    session.connect()
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/session.py", line 284, in connect
    response = self.connection.receive(request)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 617, in wrapped
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/smbprotocol/connection.py", line 929, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.ServerUnavailable: Received unexpected status from the server: The file server is temporarily unavailable. (3221226598) STATUS_SERVER_UNAVAILABLE: 0xc0000466

do you have any idea how to overcome this issue ?

**Comment by jborean93** [comment]
According to the [MS-SMB2 protocol docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-smb2/41295064-be3f-41dc-9aa5-f68545f945f0) `STATUS_SERVER_UNAVAILABLE` from the server means

> The server can return any of the following errors if the server, the file, or the share is not ready to process an I/O request from the client.

If that is the case then you need to check the logs on the server side to get a better indication as to why it's failing. It could be that your Netapp server isn't set up to deal with NTLM properly or some other issue.

The Wireshark trace you have is a bit hard to decipher what is happening. The Python traceback indicates you are connecting with `KOKO` but the Wireshark captures show a completely different user. The username part on the right hand side also seems to have a weird character for the domain separator but I'm not sure if that's just the picture not being detailed enough for me to see.

When authenticating with a domain account I usually recommend you use the UPN format `username@REALM.COM` as it works for both Kerberos and NTLM and is explicit about what domain realm account you are authenticating with. You can technically get the `DOMAIN\username` format working for NTLM auth and the underlying library should be able to handle it properly.

**Comment by natke889** [comment]
Regarding the different username its from two separate checks that I did.
I tried to use NTLM with different python library called 'pysmb' and the connection to NetApp Succeed.

![image](https://user-images.githubusercontent.com/61178350/100609902-77aca680-3317-11eb-9902-bfcbe2d2832d.png)

when using smbprotocol library I get the error
![image](https://user-images.githubusercontent.com/61178350/100609964-8a26e000-3317-11eb-9d79-c4df5a107890.png)

this is the log from NetApp

20 17:03:07 +02:00 [user_secd:debug] NSSWITCH(_nsdispatch): files, group, getgroupmembership, not found, and no fallback provided
00000001.00004607 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] .------------------------------------------------------------------------------.
00000001.00004608 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |                                 RPC FAILURE:                                 |
00000001.00004609 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |                      secd_rpc_auth_extended has failed                       |
00000001.0000460a 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |                        Result = 0, RPC Result = 7121                         |
00000001.0000460b 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |                   RPC received at Sun Nov 29 17:13:54 2020                   |
00000001.0000460c 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |------------------------------------------------------------------------------'
00000001.0000460d 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] Failure Summary:
00000001.0000460e 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] Error: User authentication procedure failed
00000001.0000460f 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] CIFS SMB2 Share mapping - Client Ip = 192.168.35.147
00000001.00004610 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] **[     0] FAILURE: CIFS authentication failed
00000001.00004611 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] Details:
00000001.00004612 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.018]  debug:  Worker Thread 34509880320 processing RPC 151:secd_rpc_auth_extended with request ID:161 which sat in the queue for 0 seconds.  { in run() at src/server/secd_rpc_server.cpp:2306 }
00000001.00004613 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.031]  debug:  Setting thread context. VServerId = 2 (name='svm_cifs'), Protocol = CIFS, lifId = 0  { in setThreadContext() at src/utils/secd_thread_data_manager.cpp:415 }
00000001.00004614 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.037]  debug:  Setting client info Module = 1  { in setThreadContextClientInfo() at src/utils/secd_thread_data_manager.cpp:512 }
00000001.00004615 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.041]  debug:  Setting client info Op = 0  { in setThreadContextClientInfo() at src/utils/secd_thread_data_manager.cpp:516 }
00000001.00004616 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.044]  debug:  Setting client info OpInstanceId = 103  { in setThreadContextClientInfo() at src/utils/secd_thread_data_manager.cpp:520 }
00000001.00004617 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.047]  debug:  Setting client info Client IP = 192.168.35.147  { in setThreadContextClientInfo() at src/utils/secd_thread_data_manager.cpp:524 }
00000001.00004618 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.053]  debug:  secd_rpc_auth_extended_1_svc called with vserver = svm_cifs  { in secd_rpc_auth_extended_1_svc() at src/authentication/secd_rpc_auth.cpp:1219 }
00000001.00004619 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.127]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_BAD_STATE:7121 in spnegoUnwrapResponseToken() at src/SpnegoCtx.cpp:1702
00000001.0000461a 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.161]  ERR  :  Found Negotiation State 3, Expected 0 or 1
00000001.0000461b 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.168]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_BAD_STATE:7121 in acceptContext() at src/SpnegoCtx.cpp:231
00000001.0000461c 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.172]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_BAD_STATE:7121 in secd_rpc_auth_extended_1_svc() at src/authentication/secd_rpc_auth.cpp:1253
00000001.0000461d 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.178]  ERR  :  CIFS authentication failed { in secd_rpc_auth_extended_1_svc() at src/authentication/secd_rpc_auth.cpp:1281 }
00000001.0000461e 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.183]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_INCONSISTENT_STATE:7123 in getUserInfo() at src/SpnegoCtx.cpp:426
00000001.0000461f 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.186]  ERR  :  MechSecurity Context is NULL
00000001.00004620 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.190]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_INCONSISTENT_STATE:7123 in secdLoadInfoForAuthRpcFailCase() at src/authentication/secd_rpc_auth.cpp:1160
00000001.00004621 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.193]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_INCONSISTENT_STATE:7123 in secd_rpc_auth_extended_1_svc() at src/authentication/secd_rpc_auth.cpp:1289
00000001.00004622 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.231]  debug:  SecD RPC Server sending reply to RPC 151: secd_rpc_auth_extended  { in secdSendRpcResponse() at src/server/secd_rpc_server.cpp:2127 }
00000001.00004623 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.000.728]  ERR  :  RESULT_ERROR_SECLIB_SPNEGO_BAD_STATE:7121 in getFailureCode() at src/utils/secd_thread_task_journal.cpp:348
00000001.00004624 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] | [000.003.796]  debug:  Logged unhandled CIFS failure code '7121' to EMS using the secd.cifsAuth.problem EMS  { in logEmsEventWithJournalForCifsAuthError() at src/utils/secd_ems_utils.cpp:1176 }
00000001.00004625 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |------------------------------------------------------------------------------.
00000001.00004626 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |                  RPC completed at Sun Nov 29 17:13:54 2020                   |
00000001.00004627 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] |               End of log for failed RPC secd_rpc_auth_extended               |
00000001.00004628 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985] '------------------------------------------------------------------------------'
00000001.00004629 00008098 Sun Nov 29 2020 17:13:54 +02:00 [kern_secd:info:12985]     

I have also tried doing the connection without encryption and without message signing but it didnt work.
I know that NetApp dont support the LdapEnforceChannelBinding if can be related.

**Comment by natke889** [comment]
I just found my issue is like 
https://github.com/jborean93/smbprotocol/issues/44

I will be happy to investigate this case with you.
If using ‘pysmb’ library with the same linux client and netapp cifs I succeed to open session with NTLMv2. 
I have network trace that we can compare if you want to.

**Comment by jborean93** [comment]
Thanks, will be good to fix this issue. Based on the server logs I think I know what is going on here. The NTLM exchange has 3 messages that are sent over 2 network hops:

* Negotiate: Sent by the client that states what NTLM features it supports
* Challenge: Sent by the server that states what features it supports based on what the client has specified, also includes a nonce and some other key values
* Authenticate: Contains the authentication information which can only be derived from your account password

Depending on the authentication protocol used the NTLM tokens could be wrapped inside an SPNEGO token and a 4th response is sent after the authenticate message that contains a MIC to verify the protocols used for authentication. The error here seems to be the SPNEGO wrapper token that wraps the NTLM authenticate message. This wrapper is called the [NegTokenResp](https://www.rfc-editor.org/rfc/rfc4178.html#section-4.2.2) and the ASN.1 structure looks like

```
NegTokenResp ::= SEQUENCE {
    negState       [0] ENUMERATED {
        accept-completed    (0),
        accept-incomplete   (1),
        reject              (2),
        request-mic         (3)
    }                                 OPTIONAL,
    -- REQUIRED in the first reply from the target
    supportedMech   [1] MechType      OPTIONAL,
    -- present only in the first reply from the target
    responseToken   [2] OCTET STRING  OPTIONAL,
    mechListMIC     [3] OCTET STRING  OPTIONAL,
    ...
}
```

In this case the authentication token based on your comment at https://github.com/jborean93/smbprotocol/issues/54#issuecomment-735431382 sent over the wire looks like:

```yaml
MessageType: SPNEGO NegTokenResp
Data:
  negState: request-mic (3)
  supportedMech:
  responseToken:
    MessageType: AUTHENTICATE_MESSAGE (3)
    Data:
      LmChallengeResponseFields:
        Len: 24
        MaxLen: 24
        BufferOffset: 80
      NtChallengeResponseFields:
        Len: 192
        MaxLen: 192
        BufferOffset: 104
      DomainNameFields:
        Len: 16
        MaxLen: 16
        BufferOffset: 296
      UserNameFields:
        Len: 26
        MaxLen: 26
        BufferOffset: 312
      WorkstationFields:
        Len: 0
        MaxLen: 0
        BufferOffset: 338
      EncryptedRandomSessionKeyFields:
        Len: 16
        MaxLen: 16
        BufferOffset: 338
      NegotiateFlags:
        raw: 1619624501
        flags:
        - NTLMSSP_NEGOTIATE_KEY_EXCH (1073741824)
        - NTLMSSP_NEGOTIATE_128 (536870912)
        - NTLMSSP_NEGOTIATE_TARGET_INFO (8388608)
        - NTLMSSP_NEGOTIATE_EXTENDED_SESSIONSECURITY (524288)
        - NTLMSSP_TARGET_TYPE_DOMAIN (65536)
        - NTLMSSP_NEGOTIATE_ALWAYS_SIGN (32768)
        - NTLMSSP_NEGOTIATE_NTLM (512)
        - NTLMSSP_NEGOTIATE_SEAL (32)
        - NTLMSSP_NEGOTIATE_SIGN (16)
        - NTLMSSP_REQUEST_TARGET (4)
        - NTLMSSP_NEGOTIATE_UNICODE (1)
      Version:
      MIC: DF02BCD4AAF855D3E465382A06297245
      Payload:
        LmChallengeResponse:
          ResponseType: LMv1
          LMProofStr: '000000000000000000000000000000000000000000000000'
        NtChallengeResponse:
          ResponseType: NTLMv2
          NTProofStr: 132F5F4F634DAE9DD3FEF3F81958A626
          ClientChallenge:
            RespType: 1
            HiRespType: 1
            Reserved1: 0
            Reserved2: 0
            TimeStamp: '2020-11-29T19:51:19.039524Z'
            ChallengeFromClient: 83ABC0B6A00D4C7C
            Reserved3: 0
            AvPairs:
            - AvId: MSV_AV_NB_COMPUTER_NAME (1)
              Value: SVM_CIFS
            - AvId: MSV_AV_NB_DOMAIN_NAME (2)
              Value: NATI
            - AvId: MSV_AV_DNS_COMPUTER_NAME (3)
              Value: SVM_CIFS.NATI.COM
            - AvId: MSV_AV_DNS_DOMAIN_NAME (4)
              Value: NATI.COM
            - AvId: MSV_AV_TARGET_NAME (9)
              Value: CIFS/192.168.35.101
            - AvId: MSV_AV_FLAGS (6)
              Value:
                raw: 2
                flags:
                - MIC_PROVIDED (2)
            - AvId: MSV_AV_EOL (0)
              Value:
            Reserved4: 0
        DomainName: nati.com
        UserName: Administrator
        Workstation:
        EncryptedRandomSessionKey: 3BF468FF20D1C1E89077E8AAD705FCC0
      SessionKey: Failed to derive
    RawData: 4E544C4D53535000030000001800180050000000C000C0006800000010001000280100001A001A00380100000000000052010000100010005201000035828960DF02BCD4AAF855D3E465382A06297245000000000000000000000000000000000000000000000000132F5F4F634DAE9DD3FEF3F81958A6260101000000000000689D670189C6D60183ABC0B6A00D4C7C0000000001001000530056004D005F004300490046005300020008004E0041005400490003002200530056004D005F0043004900460053002E004E004100540049002E0043004F004D00040010004E004100540049002E0043004F004D000900260043004900460053002F003100390032002E003100360038002E00330035002E00310030003100060004000200000000000000000000006E006100740069002E0063006F006D00410064006D0069006E006900730074007200610074006F0072003BF468FF20D1C1E89077E8AAD705FCC0
  mechListMIC: 01000000AD40B7B7E74DE11800000000
RawData: A182018730820183A0030A0103A2820166048201624E544C4D53535000030000001800180050000000C000C0006800000010001000280100001A001A00380100000000000052010000100010005201000035828960DF02BCD4AAF855D3E465382A06297245000000000000000000000000000000000000000000000000132F5F4F634DAE9DD3FEF3F81958A6260101000000000000689D670189C6D60183ABC0B6A00D4C7C0000000001001000530056004D005F004300490046005300020008004E0041005400490003002200530056004D005F0043004900460053002E004E004100540049002E0043004F004D00040010004E004100540049002E0043004F004D000900260043004900460053002F003100390032002E003100360038002E00330035002E00310030003100060004000200000000000000000000006E006100740069002E0063006F006D00410064006D0069006E006900730074007200610074006F0072003BF468FF20D1C1E89077E8AAD705FCC0A312041001000000AD40B7B7E74DE11800000000
```

_You can parse these tokens by running `pyspnego-parse --format yaml --token <base64 encoded token>`. This command should be present as pyspnego is a dep of this library._

The key part here is the `negState: request-mic (3)` field in the SPNEGO token, part of using NTLM in SPNEGO is that after the NTLM authenticate message the client expects the SPNEGO MIC response from the server so it sets the `negState` to 3. We can see in your screenshot of the logs it has the following error when it goes to process the SPNEGO response token.

> RESULT_ERROR_SECLIB_SPNEGO_BAD_STATE:7121 in spnegoUnwrapResponseToken() at src/SpnegoCtx.cpp:1702. Found Negotiation State 3, Expected 0 or 1.

So in this case the NetApp authentication acceptor is failing because the `negState` we sent was a `3` not a `0 (accept-complete)` or `1 (accept-incomplete)`. This currently works for Windows and other GSSAPI implementations and I know that Samba also works. But considering it doesn't for NetApp it means we either have a bug in pyspnego or at least we need to figure out how to work with NetApp and potentially any other vendor that also work the same way here. The question is what should be the correct behaviour.

I need to play around with some scenarios to try and figure it all out but I believe I have the logic wrong in pyspnego. I think for NTLM I always need to set `accept-incomplete (1)` and not `request-mic (3)`. I'll try and create a PR with the changes and see if you can test it out for your service and see if it works.
